databases:
  - name: walletwizard
    databaseName: walletwizard
    user: walletwizard_user

services:
  - type: web
    name: wallet-wizard
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: walletwizard
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
