default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wallet_wizard_dev
  username: postgres
  password: Takudzwa95!
  host: localhost

test:
  <<: *default
  database: wallet_wizard_test
  username: postgres
  password: Takudzwa95!
  host: localhost

production:
  <<: *default
  database: wallet_wizard_production
  username: postgres
  password: Takudzwa95!
  host: localhost
